#!/usr/bin/env python3
"""
Shared filesystem paths for BTC workflow/runtime modules.
"""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
ASSETS_DIR = PROJECT_ROOT / "assets"
BTC_ARTIFACTS_DIR = ARTIFACTS_DIR / "btc"
BTC_ASSETS_DIR = ASSETS_DIR / "btc"
LOCAL_LOGS_DIR = ARTIFACTS_DIR / "logs" / "local"

HOURLY_ARTIFACT_DIR = BTC_ARTIFACTS_DIR / "hourly"
DAILY_ARTIFACT_DIR = BTC_ARTIFACTS_DIR / "daily"
MARKET_HOURS_ARTIFACT_DIR = BTC_ARTIFACTS_DIR / "market_hours"
MARKET_HOURS_DAILY_ARTIFACT_DIR = BTC_ARTIFACTS_DIR / "market_hours_daily"

HOURLY_ASSET_DIR = BTC_ASSETS_DIR / "hourly"
DAILY_ASSET_DIR = BTC_ASSETS_DIR / "daily"
MARKET_HOURS_ASSET_DIR = BTC_ASSETS_DIR / "market_hours"
MARKET_HOURS_DAILY_ASSET_DIR = BTC_ASSETS_DIR / "market_hours_daily"

HOURLY_LAST_PREDICTION_PATH = HOURLY_ARTIFACT_DIR / "last_prediction.json"
HOURLY_HISTORY_PATH = HOURLY_ARTIFACT_DIR / "history.csv"
DAILY_LAST_PREDICTION_PATH = DAILY_ARTIFACT_DIR / "last_prediction.json"
DAILY_HISTORY_PATH = DAILY_ARTIFACT_DIR / "history.csv"
MARKET_HOURS_LAST_PREDICTION_PATH = MARKET_HOURS_ARTIFACT_DIR / "last_prediction.json"
MARKET_HOURS_HISTORY_PATH = MARKET_HOURS_ARTIFACT_DIR / "history.csv"
MARKET_HOURS_DAILY_LAST_PREDICTION_PATH = MARKET_HOURS_DAILY_ARTIFACT_DIR / "last_prediction.json"
MARKET_HOURS_DAILY_HISTORY_PATH = MARKET_HOURS_DAILY_ARTIFACT_DIR / "history.csv"

HOURLY_DASHBOARD_PATH = HOURLY_ASSET_DIR / "dashboard.png"
HOURLY_DASHBOARD_REVERSE_PATH = HOURLY_ASSET_DIR / "dashboard_reverse.png"
HOURLY_DASHBOARD_MARKET_HOURS_PATH = HOURLY_ASSET_DIR / "dashboard_market_hours.png"
HOURLY_DASHBOARD_MARKET_HOURS_REVERSE_PATH = HOURLY_ASSET_DIR / "dashboard_market_hours_reverse.png"

DAILY_DASHBOARD_PATH = DAILY_ASSET_DIR / "dashboard.png"
DAILY_DASHBOARD_REVERSE_PATH = DAILY_ASSET_DIR / "dashboard_reverse.png"
DAILY_DASHBOARD_MARKET_HOURS_PATH = DAILY_ASSET_DIR / "dashboard_market_hours.png"
DAILY_DASHBOARD_MARKET_HOURS_REVERSE_PATH = DAILY_ASSET_DIR / "dashboard_market_hours_reverse.png"

MARKET_HOURS_DASHBOARD_PATH = MARKET_HOURS_ASSET_DIR / "dashboard.png"
MARKET_HOURS_DASHBOARD_REVERSE_PATH = MARKET_HOURS_ASSET_DIR / "dashboard_reverse.png"
MARKET_HOURS_DAILY_DASHBOARD_PATH = MARKET_HOURS_DAILY_ASSET_DIR / "dashboard.png"
MARKET_HOURS_DAILY_DASHBOARD_REVERSE_PATH = MARKET_HOURS_DAILY_ASSET_DIR / "dashboard_reverse.png"

HOURLY_LOCAL_LOG_PATH = LOCAL_LOGS_DIR / "local_pipeline_run.txt"
MARKET_HOURS_LOCAL_LOG_PATH = LOCAL_LOGS_DIR / "local_market_hours_pipeline_run.txt"
MARKET_HOURS_DAILY_LOCAL_LOG_PATH = LOCAL_LOGS_DIR / "local_market_hours_daily_pipeline_run.txt"
CONSOLIDATED_LOCAL_LOG_PATH = LOCAL_LOGS_DIR / "local_consolidated_pipeline_run.txt"


def ensure_btc_output_dirs() -> None:
    for path in (
        HOURLY_ARTIFACT_DIR,
        DAILY_ARTIFACT_DIR,
        MARKET_HOURS_ARTIFACT_DIR,
        MARKET_HOURS_DAILY_ARTIFACT_DIR,
        HOURLY_ASSET_DIR,
        DAILY_ASSET_DIR,
        MARKET_HOURS_ASSET_DIR,
        MARKET_HOURS_DAILY_ASSET_DIR,
        LOCAL_LOGS_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)
